### ISSUE TITLE
Authenticate error for HA API Access from an Addon

### ISSUE THREAD

**Issue by sabeechen** [home-assistant/hassio-supervisor#1185]
**Home Assistant release with the issue:**
0.96.5

**Operating environment (HassOS/Generic):**
Unsure

**Supervisor logs:**
```
9-07-23 16:30:01 INFO (SyncWorker_14) [hassio.docker.interface] Stop addon_cebe7a76_hassio_google_drive_backup application
19-07-23 16:30:02 INFO (SyncWorker_14) [hassio.docker.interface] Clean addon_cebe7a76_hassio_google_drive_backup application
19-07-23 16:30:03 INFO (SyncWorker_14) [hassio.docker.interface] Remove image sabeechen/hassio-google-drive-backup-amd64 with latest and 0.97.4
19-07-23 16:30:10 INFO (MainThread) [hassio.addons.addon] Remove add-on data folder /data/addons/data/cebe7a76_hassio_google_drive_backup
19-07-23 16:30:14 INFO (SyncWorker_18) [hassio.docker.interface] Restart homeassistant/qemux86-64-homeassistant
19-07-23 16:30:37 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-07-23 16:30:51 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/cebe7a76_hassio_google_drive_backup
19-07-23 16:30:51 INFO (SyncWorker_5) [hassio.docker.interface] Pull image sabeechen/hassio-google-drive-backup-amd64 tag 0.97.4.
19-07-23 16:31:08 INFO (SyncWorker_5) [hassio.docker.interface] Tag image sabeechen/hassio-google-drive-backup-amd64 with version 0.97.4 as latest
19-07-23 16:32:07 INFO (SyncWorker_11) [hassio.docker.addon] Start Docker add-on sabeechen/hassio-google-drive-backup-amd64 with version 0.97.4
19-07-23 16:32:08 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-07-23 16:32:08 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/f5e8fb5e/info access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/1a1de3ed/info access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/58081dc5/info access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/1b1bb702/info access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/6331b48f/info access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/d2ee8e96/info access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:08 INFO (MainThread) [hassio.api.security] /snapshots/b8779b2a/info access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:09 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-07-23 16:32:10 WARNING (MainThread) [hassio.addons.addon] cebe7a76_hassio_google_drive_backup already running!
19-07-23 16:32:33 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-07-23 16:32:33 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-07-23 16:32:55 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
```

**Description of problem:**
I'm the author of [an addon](https://github.com/sabeechen/hassio-google-drive-backup) that backs up snapshots to Google Drive.  I haven't been able to reproduce this on any of my development instances, but at least two of my users have reported that the add-on is unable to authenticate with Home Assistant.  The supervisor logs above are from the most recent user who notified me (see [this issue](https://github.com/sabeechen/hassio-google-drive-backup/issues/79)).  The add-on makes use of both the hass.io add-on API to make/access snapshots and the Home Assistant API to publish information to sensors, but only the Home Assistant API or giving me errors.  The Hass.io Addon API is authenticating fine.

From the addon, I'm making a POST request to http://hassio/states/binary_sensor.snapshots_stale and giving the headers:
{
            'Authorization': 'Bearer ' + %HASSIO_TOKEN%
            'Client-Identifier': 'Unique Client ID'
}
This works for almost all users (at lest hundreds) but fails for some small number.  The user who saw this has attempted:
* Restarting the add-on
* Restarting Home Assistant
* Restarting the host machine
* Uninstalling and reinstalling the add-on

At least one of these worked when this happened in the past.  It might also be worth noting that the user recently restored from a snapshot, though all of the debugging mentioned has happened after that.  Any idea what I might be wrong, or if I'm using the API incorrectly form the addon?

**Comment by mokshmridul** [comment]
Hi. I'm one of the users that is facing this issue. Do let me know if there is any further information that I can provide to help address this issue.

**Comment by pvizeli** [comment]
`19-07-23 16:32:08 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!`

Look like they removed the system user for Hass.io

**Comment by mokshmridul** [comment]
I didn't remove any user, but I did do a full restore using the add-on.

**Comment by sabeechen** [comment]
Is there a way I can detect this programatically from the add-on?  I'd like to be able to give a help dialog when someone runs into this.

**Comment by mokshmridul** [comment]
Hey Guys,

is there anything i can do to help move this along?

**Comment by gribber** [comment]
I have the exact same problem, never restored a snapshot

`19-10-13 08:08:27 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-10-13 08:08:27 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-10-13 08:12:40 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-10-13 08:13:32 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-10-13 08:13:32 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale`

**Comment by pvizeli** [comment]
Do you remove the Hass.io user? How look your http HA configuration?

**Comment by gribber** [comment]
> Do you remove the Hass.io user? How look your http HA configuration?

No user is removed (hass.io is still there, system generated, adminitrator)
configuration is as following:
https://github.com/gribber/ha/blob/master/configuration.yaml

**Comment by pvizeli** [comment]
```
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.5.50.250
  base_url: !secret base_url
```

Could be that you ban the supervisor?

**Comment by gribber** [comment]
> ```
>   ip_ban_enabled: true
>   login_attempts_threshold: 3
>   use_x_forwarded_for: true
>   trusted_proxies:
>     - 10.5.50.250
>   base_url: !secret base_url
> ```
> 
> Could be that you ban the supervisor?

Good point, never thought about that and by going thru ip_bans.txt, the ip of the supervisor was found, removed and restarted HA and the errors in logs are gone
```
19-10-14 14:54:20 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
```

Also added the ip of the supervisor to trusted networks to prevent this from happening again

Thank you very much and hope this helps others too

**Comment by rourke750** [comment]
Exact same problem. This also fixed it for me.
