### ISSUE TITLE
On Pi4 some of the GPIO pins are not being set to "pull up" (activated) mode properly

### ISSUE THREAD

**Issue by skynet01** [home-assistant/hassio-supervisor#1331]
**Home Assistant release with the issue:**
HA v 0.100.2 
Supervisory 189

**Operating environment (HassOS/Generic):**
Happens on both 
HassOS and Rasspbian Buster Lite so it must be HassIO that's at fault

**Supervisor logs:**
Nothing in the logs related to this that I found

**Description of problem:**
For some reason HA doesn’t set the GPIO to pull up properly even if you state it in the config. The only way To get around this I had to manually set my GPIO pins to pullup on Pi4 boot up inside Raspbian

these are the only pins that seem to be working:

- gpio15
- gpio14
- gpio8
- gpio7
- gpio6
- gpio5
- gpio4
- gpio3
- gpio2
- gpio1
- gpio0

To verify simply try setting Pin 18 to active in config. It should show up as ON in the front end. But it doesn't: There is a thread about it here: https://community.home-assistant.io/t/hassos-raspberry-pi-4-no-gpio/138985/5

Thank you for the help!

**Comment by Misiu** [comment]
Any updates?
I need to order a new Pi for test instance of HA and I'm wondering should I go with Pi4 or Pi3 B+.
One of the requirements is working GPIO - need to connect some sensors and relays.

**Comment by skynet01** [comment]
You have to manually enable them through host os like HassOS or Raspbian. If you check that forum thread you can see how to do it

**Comment by spanishkangaroo** [comment]
> You have to manually enable them through host os like HassOS or Raspbian. If you check that forum thread you can see how to do it, it’s fairly easy

Could you please point me to that forum thread? I still don't know how to manually enable them.

**Comment by skynet01** [comment]
> > You have to manually enable them through host os like HassOS or Raspbian. If you check that forum thread you can see how to do it, it’s fairly easy
> 
> Could you please point me to that forum thread? I still don't know how to manually enable them.

Sure: https://community.home-assistant.io/t/pi-4-and-gpio-issues/137136/6?u=skynet01

**Comment by spanishkangaroo** [comment]
> > > You have to manually enable them through host os like HassOS or Raspbian. If you check that forum thread you can see how to do it, it’s fairly easy
> > 
> > 
> > Could you please point me to that forum thread? I still don't know how to manually enable them.
> 
> Sure: https://community.home-assistant.io/t/pi-4-and-gpio-issues/137136/6?u=skynet01

Thank you very much, but I am using Hassio (HassOS) so I cannot apply your fix. I've listed a bug on the Hassio repository. Let's see how it goes.

**Comment by Luoti** [comment]
> > > > You have to manually enable them through host os like HassOS or Raspbian. If you check that forum thread you can see how to do it, it’s fairly easy
> > > 
> > > 
> > > Could you please point me to that forum thread? I still don't know how to manually enable them.
> > 
> > 
> > Sure: https://community.home-assistant.io/t/pi-4-and-gpio-issues/137136/6?u=skynet01
> 
> Thank you very much, but I am using Hassio (HassOS) so I cannot apply your fix. I've listed a bug on the Hassio repository. Let's see how it goes.

Can you link the bug report you made? Or keep us posted. I want to know if there is a fix for us HassOS users too.

**Comment by spanishkangaroo** [comment]
This is the issue:
https://github.com/home-assistant/operating-system/issues/598
Anyway, I moved to Raspbian + docker Home Assistant container and my
Raspberry GPIO's work perfectly.

I miss some of the add-ons, like Mosquitto, but Hassio way too restrictive,
simple and undocumented for my needs.
