### ISSUE TITLE
phoscon - deconz double gateway 

### ISSUE THREAD

**Issue by Power84** [home-assistant/hassio-supervisor#1335]
I have installed  raspbee card on a rasperry with hass.io and after configuring the peripherals everything worked, following a reinstallation of the OS I have the following situation

 when i open the web page i can see two gateways , one with the correct id and one with id 00000000000000

if I connect to the one of available server the card does not connect and does not find peripherals

Could you please help me to solve the issue?

below are the logs:
22:54:41:530 device state timeout (handled)
22:54:42:030 wait reconnect 15 seconds
22:54:42:030 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
22:54:42:030 device state timeout ignored in state 1
22:54:43:030 wait reconnect 14 seconds
22:54:44:030 wait reconnect 13 seconds
22:54:45:030 wait reconnect 12 seconds
22:54:45:574 dev /dev/ttyAMA0
22:54:46:030 wait reconnect 11 seconds
22:54:47:030 wait reconnect 10 seconds
22:54:48:030 wait reconnect 9 seconds
22:54:49:030 wait reconnect 8 seconds
22:54:50:030 wait reconnect 7 seconds
22:54:51:029 wait reconnect 6 seconds
22:54:52:029 wait reconnect 5 seconds
22:54:53:030 wait reconnect 4 seconds
22:54:54:030 wait reconnect 3 seconds
22:54:55:030 wait reconnect 2 seconds
22:54:55:577 dev /dev/ttyAMA0
22:54:56:029 wait reconnect 1 seconds
22:54:56:067 dev /dev/ttyAMA0
22:54:56:067 COM: /dev/ttyAMA0 / serialno: 
22:54:56:067 COM: --dev: /dev/ttyAMA0 (RaspBee)
22:54:56:573 device state timeout ignored in state 2
22:54:57:530 device state timeout ignored in state 2
22:54:58:530 device state timeout ignored in state 2
22:54:59:530 device state timeout ignored in state 2
22:55:00:530 device state timeout ignored in state 2
22:55:01:530 device state timeout (handled)
22:55:02:030 wait reconnect 15 seconds
22:55:02:030 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
22:55:02:030 device state timeout ignored in state 1

thanks ALL

**Comment by pvizeli** [comment]
Yeah that is fix with 4.0 or 3.9
