### ISSUE TITLE
hass.io panel can not work

### ISSUE THREAD

**Issue by be-engineer** [home-assistant/hassio-supervisor#1353]
I installed hassio version 0.100.3,when I click left side hass.io panel, I got a message:"Unable to load the panel source: /api/hassio/app/entrypoint.js."

what can i do then?

I use command "hassio su logs", but it returned:"hassio: command not found
"
My OS is Ubuntu18.04 server

**Comment by pvizeli** [comment]
You need use the journal system of your OS to get the information they you need. `hassio-supervisor` is the systemd name.
