### ISSUE TITLE
SSH known hosts and generated keypairs stored inside container

### ISSUE THREAD

**Issue by mattfreeman1701** [home-assistant/hassio-supervisor#1366]
Hassos 2.11 on RPi3 

SSH keys for the home-assistant docker container are stored inside the container, not in a folder that can survive re-initialisation of the container.

this results in two related faults:

1. The host key is generated new every time the container initialises. This causes ECDSA host key different warning when connecting via SSH

2. Any key pairs generated for home-assistant to connect outbound via SSH (e.g. to gitlab) are lost every reboot.

this should be fixed by treating the containers /root/.ssh/ directory the same as the /config/ directory in the docker compose file.

[Id have a go, but my docker foo is terrible!]

**Comment by frenck** [comment]
We cannot do that, you should store your keys in a location that does persist.

`/config` & `/share/` are examples of locations to persist files for Hass.io, where you can store keys as well.
