### ISSUE TITLE
HASS.IO image for NUC defect

### ISSUE THREAD

**Issue by Toontje** [home-assistant/hassio-supervisor#1380]
**Home Assistant release with the issue: 2.12 for NUC downloaded from https://github.com/home-assistant/hassos/releases/download/2.12/hassos_intel-nuc-2.12.img.gz**

**Operating environment (HassOS/Generic):**
Hass OS written to USB stick using Etcher on Mac.
NUC 7i5BNH booting from this USB stick. Several USB sticks used.

**Description of problem:**
When booting from the USB stick Hass OS doesn't get passed the boot menu. 
I tried several different USB sticks all with the same result.
I tried to download several times all with the same result.
I notice that Etcher takes a long time (more than 5 minutes) to finalize the writing process.
Tried to use the same process for a Raspberry Pi and there are no problems.
I tried to write the same USB sticks with a Ubuntu image and boot from there with no problems.
It looks like the NUC image is corrupt.

**Comment by themediapot** [comment]
can i also just add to this as I've experienced identical problem: downloaded 2.12 for NUC, flashed to USB stick using balenaEtcher on mac when finalisation took a long time, tried booting Asus VivoMini UN65H using that usb, and it wouldnt get pass boot menu.

**Comment by frenck** [comment]
@themediapot, that problem is not identical, an Asus VivoMini UN65H is not a NUC.
We don't provide images for that device.

**Comment by Toontje** [comment]
Thanks for not fixing this.

**Comment by pvizeli** [comment]
HassOS can't be booted from usb stick directly
