### ISSUE TITLE
POST request >1M fail

### ISSUE THREAD

**Issue by cerebrate** [home-assistant/hassio-supervisor#1420]
**Home Assistant release with the issue:**

0.103.5

**Operating environment (HassOS/Generic):**

Debian 9 virtual machine (qemu) on antsle

**Supervisor logs:**

20-01-07 07:47:13 INFO (MainThread) [hassio.host.info] Update local host information
20-01-07 07:47:13 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-07 07:47:14 INFO (MainThread) [hassio.host.services] Update service information
20-01-07 07:47:14 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-07 07:47:14 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-01-07 07:47:14 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-01-07 08:33:53 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-01-07 09:33:53 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/korylprince/hassio-apcupsd repository
20-01-07 09:33:53 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-01-07 09:33:53 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-01-07 09:33:54 INFO (MainThread) [hassio.store] Load add-ons from store: 64 all - 0 new - 0 remove
20-01-07 09:53:53 INFO (MainThread) [hassio.host.info] Update local host information
20-01-07 09:53:53 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-07 09:53:54 INFO (MainThread) [hassio.host.services] Update service information
20-01-07 09:53:54 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-07 09:53:54 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-01-07 09:53:54 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-01-07 10:33:53 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-01-07 12:00:33 INFO (MainThread) [hassio.host.info] Update local host information
20-01-07 12:00:33 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-07 12:00:34 INFO (MainThread) [hassio.host.services] Update service information
20-01-07 12:00:34 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-07 12:00:34 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-01-07 12:00:34 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-01-07 12:33:53 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/korylprince/hassio-apcupsd repository
20-01-07 12:33:53 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-01-07 12:33:53 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-01-07 12:33:53 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-01-07 12:33:54 INFO (MainThread) [hassio.store] Load add-ons from store: 64 all - 0 new - 0 remove
20-01-07 14:07:13 INFO (MainThread) [hassio.host.info] Update local host information
20-01-07 14:07:13 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-07 14:07:14 INFO (MainThread) [hassio.host.services] Update service information
20-01-07 14:07:14 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-07 14:07:14 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-01-07 14:07:14 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-01-07 14:33:53 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json

**Description of problem:**

It appears that POST requests larger than 1M via the hassio-supervisor ingress fail.

This is an issue discovered when using the Grocy addon, one of whose features is allowing the uploading of equipment manuals. Doing so with a PDF of 5.7 MB generates a "Maximum request body size 1048576 exceeded" error; however, this is not a problem with the Grocy addon itself, as uploading this using the Grocy addon directly via port 9192 succeeds.

Could this limitation be increased to a more suitable value to enable this and similar features, say 64M?

**Comment by pvizeli** [comment]
sure
