### ISSUE TITLE
Update add-on machine config for Odroid-N2/OrangePi

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/hassio-supervisor#1430]
We need update the supported device list for add-on configs.

- Remove OrangePi
- Add Odroid

**Comment by frenck** [comment]
Removing the OrangePi from the schema would cause add-ons to be unavailable / have invalid configs that have set it.

Should we allow for a grace period or something?

**Comment by pvizeli** [comment]
They break only add-ons they tagged specific for prime. I don't think there will be any add-ons. Maybe we should set it only to `vol.Schema([str])`?
