### ISSUE TITLE
Ubuntu Server: Can't start addon_core_ssh: 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by Siytek** [home-assistant/hassio-supervisor#1437]
I decided to migrate HA from an RPi to an old MacBook Pro running Ubuntu Server. Everything works great apart from SSH server will not start. HA is latest version 195 and I get the following error in the log...

`20-01-19 12:57:14 ERROR (SyncWorker_7) [hassio.docker] Can't start addon_core_ssh: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_ssh (92a7c1b2d4b255f103ac4781ce005a713a879809a997b150bda3c8907993d137): Error starting userland proxy: listen tcp 0.0.0.0:22: bind: address already in use")`

Docker version returns...

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Ubuntu Version...

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Any help appreciated, apologies if its obvious, bit of a Linux noob. TIA

**Comment by frenck** [comment]
This is an expected error.

> listen tcp 0.0.0.0:22: bind: address already in use

This means port 22, used by SSH, is already in use. Probably cause by having SSH already running on your host system. A port can only be used once at the time.

Solution: If you want to run both at the same time: Ensure they run both on different ports.

**Comment by Siytek** [comment]
Many thanks @frenck, I had a feeling it was something simple! I changed the port and all is working now :)
