### ISSUE TITLE
yeelight "unavailable"

### ISSUE THREAD

**Issue by AsafDAVIDOF** [home-assistant/hassio-supervisor#1452]
Hello to you all
I have HA in version 0.104.3
Installed on Windows 10 on oracle VM virtualbox (ver 6.0.16)
The internet I have at home is fiber based
And my router is a netgear orbi with a satellite extension.

Everything works fine except for one really annoying thing that I don't find a solution,
Some equipment's on the network constantly have errors in the log, for example:
- Update or switch. *** is taking over 10 seconds
- Unable to discover a device at address *. *. *. *

For yeelight-based lighting fixtures, the errors are:
- Unable to update device *. *. *. *, Bedroom lightbulb: Bulb closed the connection.
- Got exception while fetching the state: Unable to discover the device *. *. *. *

these errors do not seem to affect all the equipment I have on the network, except for the yeelight lighting fixtures, from time to time these lights become "unavailable"
Sometimes for a few seconds, and often until I resate them.

What I've checked:
1. All my equipment has a fixed IP network
2. All the bulbs are in a LAN mode
3. All bulbs are connected at 2.4 Hz
4. I have disabled history / default_config / discovery / logbook on hassio
5. I disabled music mode at yeelight
6. Installation from 0 leads to the same situation

Example of Yeelight config:
``
yeelight:
  devices:
    ! secret balcony_lightbulb_ip:
      name: balcony lightbulb
      model: color2
      transition: 3
      save_on_change: False # (defaults to False)
      use_music_mode: False
    secret bedroom_lightbulb_ip:
      name: bedroom lightbulb
      model: color2
      transition: 3
      save_on_change: False # (defaults to False)
      use_music_mode: False
`
![log1](https://user-images.githubusercontent.com/43422116/73136267-46f34500-4054-11ea-8b23-7f161057f503.JPG)
`
Anyone have an idea or way to help? I'm really crazy here with all the "unavailable"

Thanks

**Comment by frenck** [comment]
Hi there,

This is the GitHub issues tracker for the Home Assistant Supervisor, not Home Assistant Core itself.

Please file an issue here: <https://github.com/home-assistant/home-assistant/issues>
